AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  CodeBuild Project Resources for Athena/Lambda Example by Marty J. Sullivan

Parameters:

  GitHubRepo:
    Type: 'String'
    Default: 'https://github.com/marty-sullivan/aws-athena-example.git'

Resources:

  BuildBucket:
    Type: 'AWS::S3::Bucket'

  BuildRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Action: 'sts:AssumeRole'
            Principal:
              Service: !Sub 'codebuild.${AWS::URLSuffix}'
      ManagedPolicyArns:
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/AWSCloudFormationReadOnlyAccess'
      Policies:
        - PolicyName: 'build-permissions'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'cloudformation:*'
                Resource:
                  - !Sub 'arn:${AWS::Partition}:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/athena-lambda-example*'
              - Effect: 'Allow'
                Action:
                  - 'codebuild:*'
                  - 'events:*'
                  - 'glue:*'
                  - 'iam:*'
                  - 'lambda:*'
                  - 'logs:*'
                  - 's3:*'
                  - 'states:*'
                Resource:
                  - '*'
  
  BuildProject:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Artifacts:
        Type: 'NO_ARTIFACTS'
      ServiceRole: !Sub '${BuildRole.Arn}'
      Source:
        Location: !Sub '${GitHubRepo}'
        Type: 'GITHUB'
        GitCloneDepth: 0
      Environment:
        ComputeType: 'BUILD_GENERAL1_SMALL'
        Image: 'aws/codebuild/python:3.7.1'
        Type: 'LINUX_CONTAINER'
        EnvironmentVariables:
          - Name: 'BUILD_BUCKET'
            Value: !Sub '${BuildBucket}'
