AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Resources for Athena/Lambda Example by Marty J. Sullivan'

Parameters:

  CenterLatitude:
    Description: 'The Latitude of the center point of the forecast; Default is Cornell University'
    Type: 'Number'
    Default: 42.4534
    MaxValue: 52.8077
    MinValue: 20.1920
    
  CenterLongitude:
    Description: 'The Latitude of the center point of the forecast; Default is Cornell University'
    Type: 'Number'
    Default: -76.4735
    MaxValue: -60.8856
    MinValue: -130.1034

Globals:
  
  Function:
    Handler: 'entry.lambda_handler'
    MemorySize: 1024
    Runtime: 'python3.7'
    Timeout: 900
    Environment:
      Variables:
        OUTPUT_BUCKET: !Sub '${OutputBucket}'

Resources:
  
  OutputBucket:
    Type: 'AWS::S3::Bucket'
  
  AthenaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: './lambda'
      Policies:
        - 'AWSLambdaBasicExecutionRole'
        - Version: '2012-10-17'
          Statement:
            - Effect: 'Allow'
              Action: 
                - 's3:GetBucketLocation'
                - 's3:GetObject'
                - 's3:ListBucket'
                - 's3:ListBucketMultipartUploads'
                - 's3:ListMultipartUploadParts'
                - 's3:AbortMultipartUpload'
                - 's3:PutObject'
                - 's3:PutObjectAcl'
              Resource:
                - !Sub '${OutputBucket.Arn}'
                - !Sub '${OutputBucket.Arn}/*'
          
  AthenaMachineRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Action: 'sts:AssumeRole'
            Principal:
              Service:
                - !Sub 'states.${AWS::URLSuffix}'
            Condition:
              StringEquals:
                'sts:ExternalId': !Sub '${AWS::AccountId}'
      Policies:
        - PolicyName: 'invoke-functions'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'lambda:InvokeFunction'
                Resource:
                  - !Sub '${AthenaFunction.Arn}'

  AthenaMachine:
    Type: 'AWS::StepFunctions::StateMachine'
    Properties:
      RoleArn: !Sub '${AthenaMachineRole.Arn}'
      DefinitionString: !Sub |-
        {
          "Comment": "State Machine for Athena Lambda Example by Marty J. Sullivan",
          "StartAt": "ExecuteAthenaQuery",
          "States": {
            "ExecuteAthenaQuery": {
              "Type": "Task",
              "Resource": "${AthenaFunction.Arn}",
              "Next": "WaitForAthenaQuery"
            },
            "WaitForAthenaQuery": {
              "Type": "Wait",
              "Seconds": 30,
              "Next": "PlotMap"
            },
            "PlotMap": {
              "Type": "Task",
              "Resource": "${AthenaFunction.Arn}",
              "End": true
            }
          }
        }